/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\my-component\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5414dea9",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5414dea9").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6c2ca5f2",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c2ca5f2").then(next)
    },
  },
  {
    name: "v-8a7399e4",
    path: "/bar/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a7399e4").then(next)
    },
  },
  {
    path: "/bar/index.html",
    redirect: "/bar/"
  },
  {
    name: "v-4808392d",
    path: "/bar/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4808392d").then(next)
    },
  },
  {
    name: "v-b3848adc",
    path: "/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3848adc").then(next)
    },
  },
  {
    name: "v-15e8eaf6",
    path: "/bar/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15e8eaf6").then(next)
    },
  },
  {
    name: "v-dcb768b0",
    path: "/foo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dcb768b0").then(next)
    },
  },
  {
    path: "/foo/index.html",
    redirect: "/foo/"
  },
  {
    name: "v-7d2b9536",
    path: "/foo/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d2b9536").then(next)
    },
  },
  {
    name: "v-6bdfadb6",
    path: "/foo/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bdfadb6").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]