/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "新宇文档",
  "description": "生命的意义不仅是活着，而是我们给别人的生命带来了何种不同。",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "shortcut icon",
        "href": "favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5414dea9",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "新建的文档",
          "slug": "新建的文档"
        },
        {
          "level": 3,
          "title": "3级标题",
          "slug": "_3级标题"
        }
      ],
      "lastUpdated": "2021/3/23 下午4:52:14"
    },
    {
      "title": "关于我们",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-6c2ca5f2",
      "path": "/about.html",
      "lastUpdated": "2021/3/23 下午4:04:22"
    },
    {
      "frontmatter": {},
      "regularPath": "/bar/",
      "relativePath": "bar/README.md",
      "key": "v-8a7399e4",
      "path": "/bar/",
      "lastUpdated": "2021/3/23 下午4:04:22"
    },
    {
      "frontmatter": {},
      "regularPath": "/bar/four.html",
      "relativePath": "bar/four.md",
      "key": "v-4808392d",
      "path": "/bar/four.html",
      "lastUpdated": "2021/3/23 下午4:04:22"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/contact.html",
      "relativePath": "contact.md",
      "key": "v-b3848adc",
      "path": "/contact.html",
      "lastUpdated": "2021/3/23 下午4:04:22"
    },
    {
      "frontmatter": {},
      "regularPath": "/bar/three.html",
      "relativePath": "bar/three.md",
      "key": "v-15e8eaf6",
      "path": "/bar/three.html",
      "lastUpdated": "2021/3/23 下午4:04:22"
    },
    {
      "title": "欢迎来到介绍页",
      "frontmatter": {},
      "regularPath": "/foo/",
      "relativePath": "foo/README.md",
      "key": "v-dcb768b0",
      "path": "/foo/",
      "lastUpdated": "2021/3/23 下午4:04:22"
    },
    {
      "title": "这是介绍配置详情页面",
      "frontmatter": {},
      "regularPath": "/foo/one.html",
      "relativePath": "foo/one.md",
      "key": "v-7d2b9536",
      "path": "/foo/one.html",
      "lastUpdated": "2021/3/23 下午4:09:51"
    },
    {
      "frontmatter": {},
      "regularPath": "/foo/two.html",
      "relativePath": "foo/two.md",
      "key": "v-6bdfadb6",
      "path": "/foo/two.html",
      "lastUpdated": "2021/3/23 下午4:04:22"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "归档",
        "link": "/archives/"
      },
      {
        "text": "分类",
        "link": "/categories/"
      },
      {
        "text": "标签",
        "link": "/tags/"
      },
      {
        "text": "关于我",
        "link": "/about/"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "sidebar": {
      "/foo/": [
        {
          "title": "介绍详情",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            ""
          ]
        },
        {
          "title": "配置详情",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            "one"
          ]
        }
      ],
      "/bar/": [
        "",
        "three",
        "four"
      ],
      "/": [
        {
          "title": "主题",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            "/"
          ]
        },
        {
          "title": "介绍",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            "/foo/"
          ],
          "initialOpenGroupIndex": -1
        }
      ]
    },
    "sidebarDepth": 2,
    "displayAllHeaders": false,
    "activeHeaderLinks": true,
    "lastUpdated": "最后更新时间",
    "repo": "pengqiang324/my-component",
    "repoLabel": "远程地址",
    "docsDir": "docs",
    "docsBranch": "main",
    "editLinks": true,
    "editLinkText": "编辑此页面"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}